### ISSUE TITLE
Spatial_Attention in Pytorch Version

### ISSUE THREAD

**Issue by zhijiejia** [GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images#10]
In Pytorch Version,  only have one Spatial_Attention，but I think there be 5 spatial_attentions is beeter.  Because there are 5 branch, and each branch should have it's own spatial_attention after channel attention. And I found there are 5 spatial_attentions in Keras Version.

![image](https://user-images.githubusercontent.com/43838913/110113350-f53bf300-7ded-11eb-9faa-d38b919d94f8.png)

**Comment by GeoZcx** [comment]
Thanks! I have just updated the code. Appreciate your reminder!
