### ISSUE TITLE
About network's output

### ISSUE THREAD

**Issue by geoyee** [GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images#13]
Sorry, my English is not very good. About your codes in pytorch version, I am comfused about a problem need your help. Why is the convolution output of the last layer of the network single channel? In remote sensing change detection. Generally, there are two types of change and non change. If output only single channel, how do we get the results of change?

**Comment by GeoZcx** [comment]
The single-channel image distinguishes the changed pixels from the unchanged pixels by pixel values. Generally, we set a threshold (e.g., 0.5) to split the pixels into two groups, values smaller than 0.5 are unchanged pixels, otherwise, are changed pixels.

**Comment by geoyee** [comment]
Thank you for your reply. But I have a question. What better way to set the threshold manually than to do argmax on two channels output? (I replied to the email, but I'm not sure you'll receive it, so I'll reply again.)
