### ISSUE TITLE
The CUDA is out of memeries. How can I solve the problems?

### ISSUE THREAD

**Issue by jaja123j** [GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images#14]
I am a beginner. I have programed the train code and the dataloader function about the dataset, and I have set the batchsize of 32, but it still out of memories, could u please tell the way to solve the memory problem?

**Comment by GeoZcx** [comment]
Hi, jaja. Generally, there are two ways to deal with the large memory cost: (1) use a small model; (2) train the model on a small dataset. I suggest you use batchsize with 16.
