### ISSUE TITLE
Problem about the output and the loss function 

### ISSUE THREAD

**Issue by jaja123j** [GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images#15]
Excuse me, i have a problem about the loss. the problem is that the output pixel of the branch is smaller than the label (such is the branch output is 28*28,but the label is 256*256),so how to deal with the label to fit the branch output pixel? i want to use downsampling...
looking foward to your reply!

**Comment by GeoZcx** [comment]
Yes. The ground truth maps are downsampled to smaller sizes to fit the branch output.
