### ISSUE TITLE
question about training process

### ISSUE THREAD

**Issue by stillwaterman** [GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images#16]
Hi, I am confused about your training process. Based on my understanding，you load 'imagenet' pretrained weights on Vgg16, then you freeze Vgg16 parameters and only train DDN part. Is my understanding right？According to the paper, I noticed that  the deep feature extraction network (DFEN) and the difference discrimination network (DDN) in the proposed method are independently trained during the training process, but if you just load 'imagenet' pretrained weights on Vgg16, you don't train Vgg16. In addition to this, if you just use pretrained weights, I question the effect of pretrained weights.

**Comment by GeoZcx** [comment]
It's true that we use the pre-trained VGG16 as the backbone of DFEN and we don't train it anymore during the later training process of DDN. The key is that the two parts **should be** trained independently. We did not do the VGG16 training process by our own, we use the one trained by others. For your concern that fixed VGG16 weights may perform worse, we force the DNN to learn how to produce change maps based on the features from VGG16, of which purpose is to maintain satisfying generalizability. Thanks!
