### ISSUE TITLE
question about DSIFN

### ISSUE THREAD

**Issue by yiyi-today** [GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images#17]
Hello, what is the role of model_A and model_B  or where is its definition, and what should be input? What did they do to "t1_input" and "t2_input" ? Thanks.
![image](https://user-images.githubusercontent.com/57097748/131776557-a508af88-26c3-4f47-9bb3-32cc525ecf7e.png)
![image](https://user-images.githubusercontent.com/57097748/131776588-01b74b0d-c7ad-47f5-b6b5-0523077bb988.png)

**Comment by GeoZcx** [comment]
The two inputs are shared pretrained networks
