### ISSUE TITLE
question about Input channel

### ISSUE THREAD

**Issue by yiyi-today** [GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images#19]
When defining the model，generally this is the form："class Unet(nn.Module):     def __init__(self, input_nbr, label_nbr):". Why is there no choice of input and output channels in your  Pytorch codes. 
![image](https://user-images.githubusercontent.com/57097748/134765867-2317afc9-e085-4031-9a77-d8749891220e.png) In your codes, “class DSIFN(nn.Module):     def __init__(self, model_A, model_B):”, model_A and model_B represent what? vgg16_base? ?
Looking forward to your answer, it will be very helpful to me. Thank you!

**Comment by GeoZcx** [comment]
Yes, represent shared vgg16 base
