### ISSUE TITLE
About Evaluation Metrics

### ISSUE THREAD

**Issue by likyoo** [GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images#2]
感谢您的工作
您在论文使用了CDD数据集，并在其测试集上取得了很好的结果。我想问一下您在计算评估指标的时候，比如用F1-Sore，那应该求出测试集中每张图片（256*256）计算出F1，再求平均；还是求出整个测试集的混淆矩阵，再算F1-Score呢？

**Comment by GeoZcx** [comment]
We use the micro F1 score.

**Comment by likyoo** [comment]
Thank you !!!
I don't know the difference between micro-f1 and f1 in binary classification.
So, the question is "Should we calculate micro F1 score for each image patch (256 * 256) in the test dataset,  and then average them; or should we calculate the confusion matrix of the whole test dataset and then calculate the micro F1 score?"

**Comment by likyoo** [comment]
If possible, could I contact you through other ways? e-mail？QQ? or wechat？
Thanks!

**Comment by GeoZcx** [comment]
We use the latter one. You can contact me via zhangchx@whu.edu.cn
