### ISSUE TITLE
question about your data set

### ISSUE THREAD

**Issue by Yeaoer** [GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images#20]
The 512x512 resultion masks in the train and val set that you released are all black. Did you train your model by upsampling the masks that resultion is 256x256, or some other methods ?

**Comment by GeoZcx** [comment]
The values on masks are 0 or 1. If you open it with some image apps, the mask images would appear all black. Please recheck the images.
