### ISSUE TITLE
Problem about the network needs to be independently trained in two steps

### ISSUE THREAD

**Issue by yiyi-today** [GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images#21]
Hello, I am very interested in your paper, but I have some problems in understanding your paper and code. Your paper said that the change detection task is divided into two stages. First, the bitemporal image is sent to the pre-trained DFEN (two VGG networks) to generate deep features, and then the extracted deep features are input into DDN to distinguish the changed areas. What do you mean by saying that these two parts should be trained independently? Does it mean to use the feature extraction method in transfer learning to extract features and then directly put them into DDN for training? You did not use the fine-tuning method, right? Hope to hear from you , thank you very much!

**Comment by GeoZcx** [comment]
Yes
