### ISSUE TITLE
数据集mask全黑

### ISSUE THREAD

**Issue by chenzek** [GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images#28]
作者您好，请问数据集mask文件全黑怎么解决呢

**Comment by songxy9037** [comment]
我也遇到了同样的问题

**Comment by chenzek** [comment]
> 我也遇到了同样的问题

他的像素值为0或1，你只需要将为1的像素改为255即可，不过事先得将mask图片位深由8改为24，再更改像素值。

**Comment by GeoZcx** [comment]
> > 我也遇到了同样的问题
> 
> 他的像素值为0或1，你只需要将为1的像素改为255即可，不过事先得将mask图片位深由8改为24，再更改像素值。

👍

**Comment by wulei1595** [comment]
> > 我也遇到了同样的问题
> 
> 他的像素值为0或1，你只需要将为1的像素改为255即可，不过事先得将mask图片位深由8改为24，再更改像素值。

具体怎么操作

**Comment by wulei1595** [comment]
> > 我也遇到了同样的问题
> 
> 他的像素值为0或1，你只需要将为1的像素改为255即可，不过事先得将mask图片位深由8改为24，再更改像素值。

为什么我位深度为8，像素值为512也是黑的
