### ISSUE TITLE
Could the raw big images be made publiced？

### ISSUE THREAD

**Issue by DwRolin** [GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images#29]
I want to do some research on change detection in big map. But there are few public change detection dataset of big map. I see the raw big maps are shown in readme. Does it mean that the raw image can be obtained by stitching, or the raw image will be made public in the future?

**Comment by GeoZcx** [comment]
> 

Hi, Rolin. Thanks for your interest in our work. 

I'm sorry that we can not provide the big map due to some issues with the dataset copyright terms.
