### ISSUE TITLE
Would you mind providing the pre-trained weights of the DSIFN？

### ISSUE THREAD

**Issue by songkq** [GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images#3]
For citing and fair comparisons, would you mind providing the pre-trained weights of the DSIFN and the predicted change maps used in the paper?

**Comment by GeoZcx** [comment]
Predicted results and model weights have been uploaded, please check path '/results'.

**Comment by songkq** [comment]
@GeoZcx  Many thanks.
