### ISSUE TITLE
Google drive or Onedrive version of dataset

### ISSUE THREAD

**Issue by farhadinima75** [GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images#30]
Hi @GeoZcx 
First of all thanks for your great repo.

Unfortunately, Beidu drive isn't available in my country.
Could you please provide a Google drive or even Onedrive version of it?

**Comment by GeoZcx** [comment]
Hi, farhadinima
Thanks for your interest in our work! 

I just uploaded the DSIFN dataset to Google drive, please see: https://drive.google.com/drive/folders/1yutLU4WI7eeeGbuxilsq2OtGQr9EHDLy?usp=sharing

**Comment by farhadinima75** [comment]
Thx.
