### ISSUE TITLE
The label of the CDD dataset is not binary map.

### ISSUE THREAD

**Issue by yiyi-today** [GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images#31]
Thank you for your generous sharing！

I found that the label of the CDD dataset was not binary map. How did you deal with this situation ?

thanks

**Comment by GeoZcx** [comment]
> 

Hi, yiyi. Thanks for your interest in this work!

The mask images are binary maps with 0 indicating unchanged pixels and 1 indicating changed pixels. Please open it with ENVI or ArcGIS to check the maps.
