### ISSUE TITLE
model

### ISSUE THREAD

**Issue by Antalia433** [GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images#32]
模型权重的链接挂了，可以再上一下吗，感谢

**Comment by GeoZcx** [comment]
我刚看了下百度网盘的链接没有挂啊，可以正常下载

**Comment by Antalia433** [comment]
> 我刚看了下百度网盘的链接没有挂啊，可以正常下载

是这个吗，https://pan.baidu.com/s/1Ae6natlx2pA3ULfC56uMkg
我这边显示的，分享的文件已经被删除。。。。。。。。

**Comment by GeoZcx** [comment]
> > 我刚看了下百度网盘的链接没有挂啊，可以正常下载
> 
> 是这个吗，https://pan.baidu.com/s/1Ae6natlx2pA3ULfC56uMkg 我这边显示的，分享的文件已经被删除。。。。。。。。

是的，旧的链接失效了，请使用新的链接：

-Link链接: https://pan.baidu.com/s/1EsVDb4FqJKLm23gHGvA77Q

-Password提取码: ru08

**Comment by Antalia433** [comment]
> 

收到，感谢~
