### ISSUE TITLE
Can you share the train code,  I am a complete beginner

### ISSUE THREAD

**Issue by WANGYong-NJ** [GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images#7]
Hi,
Thank you for sharing code.
Can you share the train code,  I am a complete beginner, and what does the f1 mean for in the load_model fun?
thank you so much!

**Comment by songyvying** [comment]
Hello, may I ask if you have got the complete code? Because I have been reading this paper recently and want to reproduce it, but because I just got into this direction and am not competent enough, I want to get the complete code to learn, thank you!
