### ISSUE TITLE
Channel Attention

### ISSUE THREAD

**Issue by zhijiejia** [GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images#8]
Thanks your new idea. There is a discrepancy with the explanation of the paper in Pytorch Version.
![image](https://user-images.githubusercontent.com/43838913/107876850-a17f6d80-6f03-11eb-948d-3ac44d05a491.png)

**Comment by GeoZcx** [comment]
Thanks for pointing out the error!
